export const PROJECTS_QUEUE_DEFAULT_JOB_ATTEMPTS = 3;
export const PROJECTS_QUEUE_DEFAULT_BACKOFF_TYPE = 'exponential';
export const PROJECTS_QUEUE_DEFAULT_BACKOFF_DELAY = 5_000;
export const PROJECTS_QUEUE_REMOVE_ON_COMPLETE = 100;
export const PROJECTS_QUEUE_REMOVE_ON_FAIL = 100;

export const PROJECTS_QUEUE_DEFAULT_JOB_OPTIONS = {
  attempts: PROJECTS_QUEUE_DEFAULT_JOB_ATTEMPTS,
  backoff: {
    type: PROJECTS_QUEUE_DEFAULT_BACKOFF_TYPE,
    delay: PROJECTS_QUEUE_DEFAULT_BACKOFF_DELAY,
  },
  removeOnComplete: PROJECTS_QUEUE_REMOVE_ON_COMPLETE,
  removeOnFail: PROJECTS_QUEUE_REMOVE_ON_FAIL,
} as const;

export const PROJECTS_QUEUE_EVENT_READY = 'ready';
export const PROJECTS_QUEUE_EVENT_COMPLETED = 'completed';
export const PROJECTS_QUEUE_EVENT_FAILED = 'failed';
export const PROJECTS_QUEUE_EVENT_ERROR = 'error';
